### ISSUE TITLE
Context menu key doesn't work

### ISSUE THREAD

**Issue by Chris2011** [mcheung63/MavenRunner#13]
As a keyboard hacker, I want to use the context menu key on my keyboard to see the context menu. This is not working, when I select a goal or a project, I can only use right click and not the context menu key.

**Comment by markiewb** [comment]
I would propose to rewrite the code to using the Nodes API. Currently it is only Swing-Hacking...

**Comment by mcheung63** [comment]
I have many years in swing but zero experience in Nodes API. start reading its tutorial

**Comment by markiewb** [comment]
@mcheung63: It was no intention to offense you. If you have Node API questions, please ask. As time allows, I will help you.

**Comment by mcheung63** [comment]
No, you did offense me :-) Forgive my bad english, i was just saying that i start reading some tutorials :-)

**Comment by mcheung63** [comment]
sorry i meant you didn't offense me, just typo

**Comment by mcheung63** [comment]
fixed, tested in windows

**Comment by Chris2011** [comment]
It is not working correctly. I think you read the mouse position to make this hack? This is my opinion because when my mouse in over a project in the mavenrunner window, and I navigate with arrow keys to an other goal, I hit the context menu key on my keyboard and the node will got the focus where my mouse is over it. But this is not the expected behaviour. The one which got the focus with the arrow keys, should got the context menu.

**Comment by markiewb** [comment]
Remove all the mouserelated event handling and use ```myComponent.setComponentPopupMenu(myPopupMenu);``` to set up the context menu!

See http://stackoverflow.com/a/8053135

**Comment by mcheung63** [comment]
fixed, please try version 3.6, sorry for late, so busy at work

**Comment by Chris2011** [comment]
It's still happening in version 4.0. Inside the maven runner window it worked, but the context is still set to the mouse position. If the mouse is everywhere else, then it doesn't work.

**Comment by Chris2011** [comment]
The context menu, shouldn't be added to the mouse, it should be added to the selected node.

**Comment by mcheung63** [comment]
Thanks for bug report, i fixed it, https://github.com/mcheung63/MavenRunner/commit/220c49c8ca8e75a6295012bb5497583a9a53978f
Will upload to netbeans plugin central. Here are the things i done:

1) Right click the node will select the node, same as "Projects" windows. When you right click the folder in projects window, it select it.
2) mouse up then click "menu" key on the keyboard, the popup show same location to that selected node

**Comment by Chris2011** [comment]
Works so far, but if nothing is selected, I got a NPE:

```
java.lang.NullPointerException
	at com.peter.mavenrunner.MavenRunnerTopComponent.projectTreeKeyReleased(MavenRunnerTopComponent.java:605)
	at com.peter.mavenrunner.MavenRunnerTopComponent.access$700(MavenRunnerTopComponent.java:102)
	at com.peter.mavenrunner.MavenRunnerTopComponent$8.keyReleased(MavenRunnerTopComponent.java:210)
	at java.awt.AWTEventMulticaster.keyReleased(AWTEventMulticaster.java:260)
	at java.awt.Component.processKeyEvent(Component.java:6496)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mcheung63** [comment]
Just fixed it, Please retest. Many many thanks for the testings.
